package keswa.domain.catalog

import keswa.core.common.AppResult
import keswa.domain.Principal

data class NewProductVariantRequest(
    val optionValues: List<OptionValueInput>,
    val nameSuffix: String,
    val costMinor: Long,
    val openingQty: Int,
    val barcodeCode: String?,
)

data class NewProductRequest(
    val code: String?,
    val nameAr: String,
    val nameEn: String?,
    val categoryId: String?,
    val brandId: String?,
    val taxRateBp: Int,
    val currencyCode: String,
    val variants: List<NewProductVariantRequest>,
)

/**
 * Creates a product and its whole variant matrix in one call. The matrix itself is generated by
 * [VariantMatrix] (called by the screen, so the owner sees a live preview) — this use case takes
 * the already-generated, owner-edited list and turns it into SKUs plus validated persistence input.
 */
class CreateProductWithVariants(
    private val products: ProductRepository,
) {
    suspend operator fun invoke(principal: Principal, request: NewProductRequest): AppResult<ProductWithVariants> {
        if (request.nameAr.isBlank()) return AppResult.Err(CatalogError.NameRequired)
        if (request.variants.isEmpty()) return AppResult.Err(CatalogError.NoVariants)

        val barcodes = request.variants.mapNotNull { it.barcodeCode?.trim()?.takeIf(String::isNotEmpty) }
        if (barcodes.size != barcodes.toSet().size) return AppResult.Err(CatalogError.DuplicateBarcode)
        for (code in barcodes) {
            if (products.isBarcodeTaken(code)) return AppResult.Err(CatalogError.DuplicateBarcode)
        }

        val productCode = request.code?.trim()?.takeIf(String::isNotEmpty) ?: products.nextProductCode()

        val variants = request.variants.mapIndexed { index, v ->
            val sku = "$productCode-${(index + 1).toString().padStart(2, '0')}"
            NewVariantInput(
                sku = sku,
                optionValues = v.optionValues,
                nameSuffix = v.nameSuffix,
                costMinor = v.costMinor,
                openingQty = v.openingQty,
                barcodeCode = v.barcodeCode?.trim()?.takeIf(String::isNotEmpty),
            )
        }
        for (v in variants) {
            if (products.isSkuTaken(v.sku)) return AppResult.Err(CatalogError.DuplicateSku)
        }

        val resolved = ResolvedNewProduct(
            code = productCode,
            nameAr = request.nameAr.trim(),
            nameEn = request.nameEn?.trim()?.takeIf(String::isNotEmpty),
            categoryId = request.categoryId,
            brandId = request.brandId,
            taxRateBp = request.taxRateBp,
            currencyCode = request.currencyCode,
            variants = variants,
        )
        return products.create(principal, resolved)
    }
}
